# Generated by Django 3.1.7 on 2021-02-21 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C19TestSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('location', models.CharField(default='n/a', max_length=100)),
                ('availability', models.CharField(choices=[('y', 'yes'), ('s', 'some'), ('n', 'no')], max_length=1)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['availability'],
            },
        ),
        migrations.CreateModel(
            name='C19VaccSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('location', models.CharField(default='n/a', max_length=100)),
                ('availability', models.CharField(choices=[('y', 'yes'), ('s', 'some'), ('n', 'no')], max_length=1)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['availability'],
            },
        ),
        migrations.CreateModel(
            name='Freedge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('location', models.CharField(default='n/a', max_length=100)),
                ('availability', models.CharField(choices=[('y', 'yes'), ('s', 'some'), ('n', 'no')], max_length=1)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['availability'],
            },
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['availability']},
        ),
        migrations.AddField(
            model_name='shelter',
            name='location',
            field=models.CharField(default='n/a', max_length=75),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='availability',
            field=models.CharField(choices=[('y', 'yes'), ('s', 'some'), ('n', 'no')], max_length=1),
        ),
    ]
