# Generated by Django 3.1.7 on 2021-02-21 12:16

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210221_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=75),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='location',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
    ]
