# Generated by Django 3.1.7 on 2021-02-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210221_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedge',
            name='phone',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(default='', max_length=45),
        ),
    ]
